name: step-size-opt-env
channels:
  - conda-forge
  - default
  - anaconda
dependencies:
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - pytest
  - salib
  - scons>=4.6
  - scipy
  - seaborn
  - waves
  - xarray