#! /usr/bin/env python

import numpy as np
import pathlib

# Inherit parent construction environment
Import("env") # type: ignore

# Set project paths
sso_package_abspath = env["sso_package_abspath"]

# Workflow variables
build_directory = pathlib.Path(Dir(".").abspath)
workflow_name = build_directory.name

# Initialize workflow to build alias for targets
workflow = []

# Define input arguments for the Gill optimizer
def my_func(x):
    try:
        return np.exp(x)/np.sqrt(np.sin(x)**3 + np.cos(x)**3)
    except RuntimeWarning:
        return 0
    except ZeroDivisionError:
        return 0

# Obtain machine precision    
evaluation_point = 1
conditional_error_bounds = (0.001, 0.1)

python_script = "gill_step_size_optimizer.py"
script_options = f"--func {my_func} "
script_options += f"--evaluation_point {evaluation_point} "
script_options += f"--conditional_error_bounds {conditional_error_bounds}"

workflow.extend(env.PythonScript(
    target = [f"test.stdout"],
    source = [f"{sso_package_abspath / python_script}"],
    subcommand_options = script_options
))

# Collector alias based on parent directory name
env.Alias(workflow_name, workflow)